---
title: "TimeSeries"
author: "Muthu Palanisamy"
date: "3/21/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Timeseries asynchronous material exercise
Following are the steps:
Download the data, I am going to use Amazon (ticker: amzn) for this analysis
Calculate log returns
Calculate Volatility measure
Calculate Volatility over entire length of series for various three different decay factors
Plot the results, overlaying the volatility curves on the data.
```{r download and plot}
require(tseries)
# Download data
AmznData<-get.hist.quote("amzn",quote="Close")
# Calculate log returns
AmznRet<-log(lag(AmznData)) - log(AmznData)
#Calculate Volatility Measure.
AmznVol<-sd(AmznRet) * sqrt(250) * 100
#Calculate Volatility over entire length
Vol<-function(d,logrets){
  var = 0
  lam = 0
  varlist<-c()
  for (r in logrets){
    lam = lam * (1 - 1/d) + 1
    var = (1 - 1/lam)*var + (1/lam) * r^2
    varlist<-c(varlist,var)
  }
  sqrt(varlist)
}
# Plot the results
volest<-Vol(10, AmznRet)
volest2<-Vol(30,AmznRet)
volest3<-Vol(100,AmznRet)

plot(volest,type="l")
lines(volest2,type="l",col="red")
lines(volest3,type="l",col="blue")
```
